aws:
  bucket_name: cloud-project-2
  prefix: artifacts
  upload: true
create_dataset:
  encode_and_split:
    Blood Pressure:
      new_columns:
      - Systolic_BP
      - Diastolic_BP
      original_column: Blood Pressure
      separator: /
  encode_categorical:
    Diet:
      mapping:
        Average: 0
        Healthy: 1
        Unhealthy: 2
    Hemisphere:
      mapping:
        Northern Hemisphere: 1
        Southern Hemisphere: 0
  one_hot_encode:
  - Continent
  remove_columns:
  - Patient ID
  - Country
environment:
  auto_reload: true
  backend_figure_format: retina
  matplotlib_backend: inline
evaluate_performance:
  metrics:
  - auc
  - accuracy
  - confusion
  - classification_report
generate_features:
  features:
  - Age
  - Cholesterol
  - Heart Rate
  - Diabetes
  - Family History
  - Smoking
  - Obesity
  - Alcohol Consumption
  - Exercise Hours Per Week
  - Diet_encoded
  - Systolic_BP
  - Diastolic_BP
  scaler: StandardScaler
plotting:
  figure_size:
  - 12.0
  - 8.0
  font_family: sans-serif
  font_size: 16
  label_color: '#677385'
  label_size: 20
  line_color: '#0055A7'
  line_width: 3
  sans_serif_font: Tahoma
  text_color: '#677385'
  tick_labelsize: 14
  title_size: 20
run_config:
  author: Kira Luo
  data_source: s3://cloud-project-2/raw_data/Raw_Data_heart_attack_prediction_dataset.csv
  dependencies: requirements.txt
  description: Classifies patients into high risk (1) or low risk of a heart attack
    (0).
  name: random-forest-heart_attack_classification
  version: 1.0
score_model:
  choose_features:
    features_to_use:
    - Age
    - Cholesterol
    - Heart Rate
    - Diabetes
    - Family History
    - Smoking
    - Obesity
    - Alcohol Consumption
    - Exercise Hours Per Week
    - Diet_encoded
    - Systolic_BP
    - Diastolic_BP
  method: random_forest
train_model:
  choose_features:
    features_to_use:
    - Age
    - Cholesterol
    - Heart Rate
    - Diabetes
    - Family History
    - Smoking
    - Obesity
    - Alcohol Consumption
    - Exercise Hours Per Week
    - Diet_encoded
    - Systolic_BP
    - Diastolic_BP
  get_target:
    target: Heart Attack Risk
  method: random_forest
  parameters:
    max_depth: 40
    max_features: 5
    min_samples_leaf: 4
    n_estimators: 400
  split_data:
    test_size: 0.2
    train_size: 0.8
